/* 0x00 */
OP( NOP, 1 )
OP( LD_BC_NN, 1 )
OP( LD_RBC_A, 1 )
OP( INC_BC, 1 )
OP( INC_B, 1 )
OP( DEC_B, 1 )
OP( LD_B_N, 1 )
OP( RLCA, 1 )
OP( EX_AF_AF, 1 )
OP( ADD_HL_BC, 1 )
OP( LD_A_RBC, 1 )
OP( DEC_BC, 1 )
OP( INC_C, 1 )
OP( DEC_C, 1 )
OP( LD_C_N, 1 )
OP( RRCA, 1 )

/* 0x10 */
OP( DJNZ_N, 1 )
OP( LD_DE_NN, 1 )
OP( LD_RDE_A, 1 )
OP( INC_DE, 1 )
OP( INC_D, 1 )
OP( DEC_D, 1 )
OP( LD_D_N, 1 )
OP( RLA, 1 )
OP( JR_N, 1 )
OP( ADD_HL_DE, 1 )
OP( LD_A_RDE, 1 )
OP( DEC_DE, 1 )
OP( INC_E, 1 )
OP( DEC_E, 1 )
OP( LD_E_N, 1 )
OP( RRA, 1 )

/* 0x20 */
OP( JR_NZ_N, 1 )
OP( LD_HL_NN, 1 )
OP( LD_RNN_HL, 1 )
OP( INC_HL, 1 )
OP( INC_H, 1 )
OP( DEC_H, 1 )
OP( LD_H_N, 1 )
OP( DAA, 1 )
OP( JR_Z_N, 1 )
OP( ADD_HL_HL, 1 )
OP( LD_HL_RNN, 1 )
OP( DEC_HL, 1 )
OP( INC_L, 1 )
OP( DEC_L, 1 )
OP( LD_L_N, 1 )
OP( CPL, 1 )

/* 0x30 */
OP( JR_NC_N, 1 )
OP( LD_SP_NN, 1 )
OP( LD_RNN_A, 1 )
OP( INC_SP, 1 )
OP( INC_RHL, 1 )
OP( DEC_RHL, 1 )
OP( LD_RHL_N, 1 )
OP( SCF, 1 )
OP( JR_C_N, 1 )
OP( ADD_HL_SP, 1 )
OP( LD_A_RNN, 1 )
OP( DEC_SP, 1 )
OP( INC_A, 1 )
OP( DEC_A, 1 )
OP( LD_A_N, 1 )
OP( CCF, 1 )

/* 0x40 */
OP( LD_B_B, 1 )
OP( LD_B_C, 1 )
OP( LD_B_D, 1 )
OP( LD_B_E, 1 )
OP( LD_B_H, 1 )
OP( LD_B_L, 1 )
OP( LD_B_RHL, 1 )
OP( LD_B_A, 1 )
OP( LD_C_B, 1 )
OP( LD_C_C, 1 )
OP( LD_C_D, 1 )
OP( LD_C_E, 1 )
OP( LD_C_H, 1 )
OP( LD_C_L, 1 )
OP( LD_C_RHL, 1 )
OP( LD_C_A, 1 )

/* 0x50 */
OP( LD_D_B, 1 )
OP( LD_D_C, 1 )
OP( LD_D_D, 1 )
OP( LD_D_E, 1 )
OP( LD_D_H, 1 )
OP( LD_D_L, 1 )
OP( LD_D_RHL, 1 )
OP( LD_D_A, 1 )
OP( LD_E_B, 1 )
OP( LD_E_C, 1 )
OP( LD_E_D, 1 )
OP( LD_E_E, 1 )
OP( LD_E_H, 1 )
OP( LD_E_L, 1 )
OP( LD_E_RHL, 1 )
OP( LD_E_A, 1 )

/* 0x60 */
OP( LD_H_B, 1 )
OP( LD_H_C, 1 )
OP( LD_H_D, 1 )
OP( LD_H_E, 1 )
OP( LD_H_H, 1 )
OP( LD_H_L, 1 )
OP( LD_H_RHL, 1 )
OP( LD_H_A, 1 )
OP( LD_L_B, 1 )
OP( LD_L_C, 1 )
OP( LD_L_D, 1 )
OP( LD_L_E, 1 )
OP( LD_L_H, 1 )
OP( LD_L_L, 1 )
OP( LD_L_RHL, 1 )
OP( LD_L_A, 1 )

/* 0x70 */
OP( LD_RHL_B, 1 )
OP( LD_RHL_C, 1 )
OP( LD_RHL_D, 1 )
OP( LD_RHL_E, 1 )
OP( LD_RHL_H, 1 )
OP( LD_RHL_L, 1 )
OP( HALT, 1 )
OP( LD_RHL_A, 1 )
OP( LD_A_B, 1 )
OP( LD_A_C, 1 )
OP( LD_A_D, 1 )
OP( LD_A_E, 1 )
OP( LD_A_H, 1 )
OP( LD_A_L, 1 )
OP( LD_A_RHL, 1 )
OP( LD_A_A, 1 )

/* 0x80 */
OP( ADD_A_B, 1 )
OP( ADD_A_C, 1 )
OP( ADD_A_D, 1 )
OP( ADD_A_E, 1 )
OP( ADD_A_H, 1 )
OP( ADD_A_L, 1 )
OP( ADD_A_RHL, 1 )
OP( ADD_A_A, 1 )
OP( ADC_A_B, 1 )
OP( ADC_A_C, 1 )
OP( ADC_A_D, 1 )
OP( ADC_A_E, 1 )
OP( ADC_A_H, 1 )
OP( ADC_A_L, 1 )
OP( ADC_A_RHL, 1 )
OP( ADC_A_A, 1 )

/* 0x90 */
OP( SUB_A_B, 1 )
OP( SUB_A_C, 1 )
OP( SUB_A_D, 1 )
OP( SUB_A_E, 1 )
OP( SUB_A_H, 1 )
OP( SUB_A_L, 1 )
OP( SUB_A_RHL, 1 )
OP( SUB_A_A, 1 )
OP( SBC_A_B, 1 )
OP( SBC_A_C, 1 )
OP( SBC_A_D, 1 )
OP( SBC_A_E, 1 )
OP( SBC_A_H, 1 )
OP( SBC_A_L, 1 )
OP( SBC_A_RHL, 1 )
OP( SBC_A_A, 1 )

/* 0xA0 */
OP( AND_B, 1 )
OP( AND_C, 1 )
OP( AND_D, 1 )
OP( AND_E, 1 )
OP( AND_H, 1 )
OP( AND_L, 1 )
OP( AND_RHL, 1 )
OP( AND_A, 1 )
OP( XOR_B, 1 )
OP( XOR_C, 1 )
OP( XOR_D, 1 )
OP( XOR_E, 1 )
OP( XOR_H, 1 )
OP( XOR_L, 1 )
OP( XOR_RHL, 1 )
OP( XOR_A, 1 )

/* 0xB0 */
OP( OR_B, 1 )
OP( OR_C, 1 )
OP( OR_D, 1 )
OP( OR_E, 1 )
OP( OR_H, 1 )
OP( OR_L, 1 )
OP( OR_RHL, 1 )
OP( OR_A, 1 )
OP( CP_B, 1 )
OP( CP_C, 1 )
OP( CP_D, 1 )
OP( CP_E, 1 )
OP( CP_H, 1 )
OP( CP_L, 1 )
OP( CP_RHL, 1 )
OP( CP_A, 1 )

/* 0xC0 */
OP( RET_NZ, 1 )
OP( POP_BC, 1 )
OP( JP_NZ_NN, 1 )
OP( JP_NN, 1 )
OP( CALL_NZ_NN, 1 )
OP( PUSH_BC, 1 )
OP( ADD_A_N, 1 )
OP( RST_00, 1 )
OP( RET_Z, 1 )
OP( RET, 1 )
OP( JP_Z_NN, 1 )
OP( PREFIX_CB, 1 )
OP( CALL_Z_NN, 1 )
OP( CALL_NN, 1 )
OP( ADC_A_N, 1 )
OP( RST_08, 1 )

/* 0xD0 */
OP( RET_NC, 1 )
OP( POP_DE, 1 )
OP( JP_NC_NN, 1 )
OP( OUT_RN_A, 1 )
OP( CALL_NC_NN, 1 )
OP( PUSH_DE, 1 )
OP( SUB_A_N, 1 )
OP( RST_10, 1 )
OP( RET_C, 1 )
OP( EXX, 1 )
OP( JP_C_NN, 1 )
OP( IN_A_RN, 1 )
OP( CALL_C_NN, 1 )
OP( PREFIX_DD, 1 )
OP( SBC_A_N, 1 )
OP( RST_18, 1 )

/* 0xE0 */
OP( RET_PO, 1 )
OP( POP_HL, 1 )
OP( JP_PO_NN, 1 )
OP( EX_RSP_HL, 1 )
OP( CALL_PO_NN, 1 )
OP( PUSH_HL, 1 )
OP( AND_N, 1 )
OP( RST_20, 1 )
OP( RET_PE, 1 )
OP( JP_HL, 1 )
OP( JP_PE_NN, 1 )
OP( EX_DE_HL, 1 )
OP( CALL_PE_NN, 1 )
OP( PREFIX_ED, 1 )
OP( XOR_N, 1 )
OP( RST_28, 1 )

/* 0xF0 */
OP( RET_P, 1 )
OP( POP_AF, 1 )
OP( JP_P_NN, 1 )
OP( DI, 1 )
OP( CALL_P_NN, 1 )
OP( PUSH_AF, 1 )
OP( OR_N, 1 )
OP( RST_30, 1 )
OP( RET_M, 1 )
OP( LD_SP_HL, 1 )
OP( JP_M_NN, 1 )
OP( EI, 1 )
OP( CALL_M_NN, 1 )
OP( PREFIX_FD, 1 )
OP( CP_N, 1 )
OP( RST_38, 1 )

